#  Copyright (c) 2018 5GTANGO, Paderborn University
# ALL RIGHTS RESERVED.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Neither the name of the SONATA-NFV, 5GTANGO, Paderborn University
# nor the names of its contributors may be used to endorse or promote
# products derived from this software without specific prior written
# permission.
#
# This work has also been performed in the framework of the 5GTANGO project,
# funded by the European Commission under Grant number 761493 through
# the Horizon 2020 and 5G-PPP programmes. The authors would like to
# acknowledge the contributions of their colleagues of the SONATA
# partner consortium (www.5gtango.eu).


# 1 CNF = 1 service and 1 deployment (=1 pod) with separate containers per CDU
apiVersion: v1
kind: Service
metadata:
  #namespace: sm
  name: ns2-mdc-svc
  # for easy reference later on
  labels:
    pilot: sm
    ns: ns2
    cnf: mdc
spec:
  # to which deployment does this service belong?
  selector:
    pilot: sm
    ns: ns2
    cnf: mdc
  # this requires MetalLB (or another LB) to be installed and configured
  type: LoadBalancer
  ports:
    # don't need the UDP ports
    - name: samba139
      protocol: TCP
      port: 139
    - name: samba445
      protocol: TCP
      port: 445
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: sm
  name: ns2-mdc
  labels:
    pilot: sm
    ns: ns2
    cnf: mdc
spec:
  selector:
    # must match the labels of the template
    matchLabels:
      pilot: sm
      ns: ns2
      cnf: mdc
  # the pod(s) to deploy = 1 CDU
  template:
    metadata:
      labels:
        pilot: sm
        ns: ns2
        cnf: mdc
    spec:
      containers:
      - name: vnf-mdc
        image: sonatanfv/vnf-mdc:k8s
        imagePullPolicy: IfNotPresent
        env:
        # the k8s service names of all CNFs need to be set by the SP dynamically
        - name: MQTT_BROKER_HOST
          value: ns1-cc-service
        - name: MQTT_BROKER_PORT
          value: "1883"
