version: '3'

# docker network create --driver=bridge --subnet=172.23.0.0/23 --gateway=172.23.0.1 --ip-range=172.23.0.128/25 tango

services:

  suricata-ids:
    build: .
    container_name: suricata
    network_mode: host
#    networks:
#      - default

#  dns:
#    image: phensley/docker-dns
#    #image: rancher/dns
#    container_name: mydns
#    networks:
#      - default

  logstash:
    # a tool for managing events and logs:  https://www.elastic.co/guide/en/logstash/current/docker-config.html
    image: docker.elastic.co/logstash/logstash:6.6.0
    container_name: logstash
    network_mode: host
#    networks:
#      - default
    environment:
      - PIPELINE_WORKERS="2"
      #- LOG_LEVEL="log.level"
      #- XPACK_MONITORING_ENABLED="xpack.monitoring.enabled"
      - xpack.monitoring.elasticsearch.url="http://localhost:9200"
    volumes:
      - lsdata:/usr/share/logstash/pipeline

  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    network_mode: host
#    networks:
#      - default
    ports:
      - "9200:9200/tcp"
      - "9300:9300/udp"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    network_mode: host
#    networks:
#      - default
    ports:
      - "5601:5601/tcp"
    environment:
      - ELASTICSEARCH_URL="http://localhost:9200"

volumes:
  esdata:
    driver: local
  lsdata:
    driver: local

networks:
  default:
    external:
      name: tango

#configs:
#  selk_config:
#    - '${SELK_DATA}:/etc/selk'

