# YOU MUST CHANGE THE NETWORK INTERFACE NAME TO YOUR's
# ex: eth0 --> enp3s0
---
apiVersion: v1
kind: Pod
metadata:
  namespace: smp-dev
  name: suricata-ids
  labels:
    app: suricata-ids
spec:
  containers:
  - name: suricata-ids
    image: jasonish/suricata
    imagePullPolicy: IfNotPresent
    args: ["-i eth0"]
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:7.3.1
    imagePullPolicy: IfNotPresent
  restartPolicy: Never
  hostNetwork: true